#Select the backend to use.
#Allowed Values: OFF, BATCHING, INSTANCING
backend = "OFF"
#Enable or disable a debug overlay that colors pixels by their normal.
debugNormals = true
#Enable or disable instance update limiting with distance.
limitUpdates = true

